# Generated by Django 3.1.2 on 2020-12-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201221_1734'),
        ('contact', '0002_auto_20201221_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='associated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.login'),
        ),
    ]
