# Generated by Django 3.1.2 on 2020-12-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201221_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zipcode',
            field=models.IntegerField(default=94539),
            preserve_default=False,
        ),
    ]
