# Generated by Django 3.1.2 on 2020-12-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='city',
            field=models.CharField(default='Milpitas', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='fname',
            field=models.CharField(default='Bob', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='house_number',
            field=models.IntegerField(default=41922),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='lname',
            field=models.CharField(default='Jones', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='state',
            field=models.CharField(default='CA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='street',
            field=models.CharField(default='Via San Carlos', max_length=200),
            preserve_default=False,
        ),
    ]
